In [63]:
#pip install xgboost

In [64]:
import pandas as pd
import xgboost

In [65]:
df_price = pd.read_csv("../data/with_price.csv")
df_noprice = pd.read_csv("../data/without_price.csv")

In [66]:
df_train = df_price.drop(["Island_Name", "Country", "nearest_city"], axis=1)
df_train

,Acreage,latitude,longitude,Large Acreage,Ocean Island,Income Potential,Mainland Power,Islands with Beaches,Turn Key,Airstrip or Fly-in,Income Producing,Lake Island,Seasonal,Historic,River Island,Mainland Lot,city_distance,price
0,110,7.954390,98.447306,1,1,1,0,1,0,0,0,0,0,0,0,0,3.69,1.600000e+08
1,26,24.713197,-81.554253,1,1,1,0,0,1,0,0,0,0,0,0,0,4.54,9.500000e+07
2,460,24.358032,-76.582153,1,1,1,0,1,0,0,0,0,0,0,0,0,60.10,6.200000e+07
3,222,23.901611,-76.263142,1,1,1,0,1,1,0,0,0,0,0,0,0,40.22,6.000000e+07
4,2223,-18.753102,-141.807896,1,1,1,0,1,0,1,0,0,0,0,0,0,1178.30,5.577867e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,0,18.203379,-88.005036,0,0,0,0,0,0,0,0,0,0,0,0,0,20.02,6.950000e+04
436,12,44.459238,-64.161885,0,1,0,0,0,0,0,0,0,1,0,0,0,6.88,6.810443e+04
437,6,45.588639,-61.207668,0,0,0,0,1,0,0,0,1,0,0,0,1,7.08,5.902384e+04
438,0,17.221948,-87.593735,0,0,0,0,0,0,0,0,0,0,0,0,0,44.20,5.900000e+04
439,0,41.788300,-82.797509,0,0,0,0,0,0,0,0,0,0,0,0,0,20.42,2.570000e+04

In [67]:
df_test = df_noprice.drop(["price", "Island_Name", "Country", "nearest_city"], axis=1)
df_test

,Acreage,latitude,longitude,Large Acreage,Ocean Island,Income Potential,Mainland Power,Islands with Beaches,Turn Key,Airstrip or Fly-in,Lake Island,Seasonal,Historic,River Island,Mainland Lot,city_distance
0,643,37.653723,23.949079,1,1,1,1,0,0,0,0,0,0,0,0,4.58
1,42,5.852108,73.336561,1,1,1,0,1,1,0,0,0,0,0,0,7.92
2,21,53.455764,15.919065,1,0,1,0,0,1,0,1,1,1,0,0,4.25
3,32,38.986346,20.917405,1,1,0,0,0,0,0,0,0,0,0,0,5.11
4,0,25.051382,-76.121848,1,1,1,0,0,1,0,0,0,1,0,0,40.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,2,18.318585,-64.958120,0,1,1,0,0,1,0,0,0,0,0,0,153.16
240,46,24.184307,-76.441174,1,1,1,0,1,1,0,0,0,0,0,0,57.11
241,26247,-51.286789,-59.652042,1,1,1,0,1,0,1,0,0,1,0,0,371.38
242,40,16.489920,-88.214336,1,1,1,0,0,1,0,0,0,0,0,0,10.22
243,3,16.550108,-88.084820,0,1,0,0,1,0,0,0,0,0,0,0,18.82

In [68]:
x_train = df_train.drop(["price"], axis=1)
y_train = df_train["price"]

In [69]:
classifier = xgboost.XGBRegressor()
classifier.fit(x_train, y_train)

[19:32:13] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [70]:
y_pred = classifier.predict(df_test)

ValueError: feature_names mismatch: ['Acreage', 'latitude', 'longitude', 'Large Acreage', 'Ocean Island', 'Income Potential', 'Mainland Power', 'Islands with Beaches', 'Turn Key', 'Airstrip or Fly-in', 'Income Producing', 'Lake Island', 'Seasonal', 'Historic', 'River Island', 'Mainland Lot', 'city_distance'] ['Acreage', 'latitude', 'longitude', 'Large Acreage', 'Ocean Island', 'Income Potential', 'Mainland Power', 'Islands with Beaches', 'Turn Key', 'Airstrip or Fly-in', 'Lake Island', 'Seasonal', 'Historic', 'River Island', 'Mainland Lot', 'city_distance']
expected Income Producing in input data

In [ ]:
df_noprice["price"] = y_pred

In [71]:
df_noprice

,Island_Name,Acreage,Country,latitude,longitude,Large Acreage,Ocean Island,Income Potential,Mainland Power,Islands with Beaches,...,Airstrip or Fly-in,Income Producing,Lake Island,Seasonal,Historic,River Island,Mainland Lot,nearest_city,city_distance,price
0,Island of Patroklos,643,Greece,37.653723,23.949079,1,1,1,1,0,...,0,0,0,0,0,0,0,PalaiÃ¡ FÃ³kaia,4.58,NaN
1,Kandoo Island,42,Maldives,5.852108,73.336561,1,1,1,0,1,...,0,1,0,0,0,0,0,Manadhoo,7.92,NaN
2,Schulzewerder Island,21,Poland,53.455764,15.919065,1,0,1,0,0,...,0,1,1,1,1,0,0,Powiat drawski,4.25,NaN
3,Vouvalos Island,32,Greece,38.986346,20.917405,1,1,0,0,0,...,0,0,0,0,0,0,0,VÃ³nitsa,5.11,NaN
4,Windermere,0,Bahamas,25.051382,-76.121848,1,1,1,0,0,...,0,1,0,0,1,0,0,Arthurâ€™s Town,40.94,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,Water Island Peninsula,2,United States of America,18.318585,-64.958120,0,1,1,0,0,...,0,0,0,0,0,0,0,Saint Paulâ€™s,153.16,NaN
240,Private Island Exuma,46,Bahamas,24.184307,-76.441174,1,1,1,0,1,...,0,0,0,0,0,0,0,Arthurâ€™s Town,57.11,NaN
241,Pebble Island,26247,Falkland Islands,-51.286789,-59.652042,1,1,1,0,1,...,1,1,0,0,1,0,0,Puerto Deseado,371.38,NaN
242,Long Caye Private Island,40,Belize,16.489920,-88.214336,1,1,1,0,0,...,0,0,0,0,0,0,0,Placencia,10.22,NaN
243,Funk Caye,3,Belize,16.550108,-88.084820,0,1,0,0,1,...,0,0,0,0,0,0,0,Placencia,18.82,NaN

In [62]:
df_noprice["predicted"] = "yes"
df_price["predicted"] = "no"
df_final = df_price.append(df_noprice)
df_final.to_csv("../data/island_final_price.csv")