In [9]:
import pandas as pd
df = pd.read_csv("../data/island_info.csv")
df

,Island_Name,Acreage,Country,latitude,longitude,Large Acreage,Ocean Island,Income Potential,Mainland Power,Islands with Beaches,...,Airstrip or Fly-in,Income Producing,Lake Island,Seasonal,Historic,River Island,Mainland Lot,nearest_city,city_distance,price
0,Island of Patroklos,643,Greece,37.653723,23.949079,yes,yes,yes,yes,no,...,no,no,no,no,no,no,no,Palaiá Fókaia,4.58,NaN
1,Rangyai Island,110,Thailand,7.954390,98.447306,yes,yes,yes,no,yes,...,no,no,no,no,no,no,no,Ban Ko Kaeo,3.69,160000000.0
2,Pumpkin Key,26,United States of America,24.713197,-81.554253,yes,yes,yes,no,no,...,no,no,no,no,no,no,no,Cudjoe Key,4.54,95000000.0
3,Spectabilis Island,460,Bahamas,24.358032,-76.582153,yes,yes,yes,no,yes,...,no,no,no,no,no,no,no,Arthur’s Town,60.10,62000000.0
4,Cave Cay,222,Bahamas,23.901611,-76.263142,yes,yes,yes,no,yes,...,no,no,no,no,no,no,no,George Town,40.22,60000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,Water Island Peninsula,2,United States of America,18.318585,-64.958120,no,yes,yes,no,no,...,no,no,no,no,no,no,no,Saint Paul’s,153.16,NaN
680,Private Island Exuma,46,Bahamas,24.184307,-76.441174,yes,yes,yes,no,yes,...,no,no,no,no,no,no,no,Arthur’s Town,57.11,NaN
681,Pebble Island,26247,Falkland Islands,-51.286789,-59.652042,yes,yes,yes,no,yes,...,yes,yes,no,no,yes,no,no,Puerto Deseado,371.38,NaN
682,Long Caye Private Island,40,Belize,16.489920,-88.214336,yes,yes,yes,no,no,...,no,no,no,no,no,no,no,Placencia,10.22,NaN
683,Funk Caye,3,Belize,16.550108,-88.084820,no,yes,no,no,yes,...,no,no,no,no,no,no,no,Placencia,18.82,NaN

In [10]:
new_dict = {}
attributes = []

for column in df:
    attributes = []
    column_list = df[column].tolist()
    for item in column_list:
        if item == "yes":
            attribute = 1
        elif item == "no":
            attribute = 0
        else:
            attribute = item
        attributes.append(attribute)
    
    new_dict[column] = attributes

new_df = pd.DataFrame(new_dict)
df = new_df

In [11]:
df2 = df.dropna(subset=["price"])
df2.to_csv("../data/with_price.csv", index=False)

In [12]:
price_list = df["price"].tolist()
counter = 0
index_list = []

for item in price_list:
    if item > 1:
        index_list.append(counter)
    else:
        pass
    
    counter = counter+1

index_list.reverse()

nan_dict = {}

for column in df:
    column_list = df[column].tolist()
    for item in index_list:
        column_list.pop(item)
    nan_dict[column] = column_list

df3 = pd.DataFrame(nan_dict)
df3.to_csv("../data/without_price.csv", index=False)